spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
       url : jdbc:h2:file:./data/hsweb
       username : sa
       password :
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name : org.h2.Driver
    cache:
       type: simple

hsweb:
    authorize:
#      filters:
#           "/swagger-ui.html": "authc"
    app:
      name: hsweb演示
      version: 3.0.0
    entity: # 自定义实体类型映射,可通过此方式自定义字段
      mappings:
          -  source-base-package: org.hswebframework.web.entity.authorization
             target-base-package: org.hswebframework.web.entity.authorization
             mapping:
                UserEntity: SimpleUserEntity  #UserEntity使用SimpleUserEntity实现
server:
  port: 8081
mybatis:
#  mapper-location-excludes: classpath*:**/UserMapper.xml  # 不加载的配置
  mapper-locations: classpath*:org/hswebframework/web/demo/mappers/**/*.xml